### ISSUE TITLE
Blog Feature - Para Bundle

### ISSUE THREAD

**Issue by yasmeenfahmy** [bluecadet/longwood-d8#199] opened 2021-10-27 20:47 UTC
[Figma Comp (2)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A1869)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/37923c14-4b3e-4353-b61f-299a583da298)

[Figma Comp (3)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A1977)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/cca6ae53-a9f3-4952-863d-44d70169b97f)

[Figma Comp (4)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=521%3A2452)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/3cac6aa3-f17e-4e3b-94d7-9a2defbad64a)

[Figma Comp (5)
](https://www.figma.com/file/EdjEX63xgzWlbhQXeXYhbF/Production?node-id=425%3A1797)
Screenshot:
![image.png](https://images.zenhubusercontent.com/60aebf7546d844ffb3496014/9b7ce008-7855-4058-9417-915d8b4bc41f)

**Comment by pingevt** [comment] 2022-01-26 13:09
Duplicate of #127

**Closed by pingevt** 2022-01-26 13:09 UTC
Labels: back end
